version: "2"
linters:
  default: all
  disable:
    - exhaustive
    - exhaustruct
    - lll
    - testpackage
    - varnamelen
    - wsl
    - godox # FIXME

  settings:
    cyclop:
      max-complexity: 30
      package-average: 0
    ireturn:
      allow:
        - anon
        - error
        - empty
        - stdlib
    depguard:
      rules:
        main:
          list-mode: strict
          files:
            - $all
            - "!$test"
          allow:
            - $gostd
            - github.com/go-sql-driver/mysql
            - github.com/lmittmann/tint
            - github.com/persona-id/proxysql-agent/
            - github.com/spf13/pflag
            - github.com/spf13/viper
            - github.com/yassinebenaid/godump
            - k8s.io/api/core/v1
            - k8s.io/apimachinery/pkg/apis/meta/v1
            - k8s.io/apimachinery/pkg/labels
            - k8s.io/apimachinery/pkg/types
            - k8s.io/apimachinery/pkg/util/runtime
            - k8s.io/apimachinery/pkg/util/wait
            - k8s.io/client-go/informers
            - k8s.io/client-go/kubernetes
            - k8s.io/client-go/rest
            - k8s.io/client-go/tools/cache
            - k8s.io/client-go/tools/record
            - k8s.io/client-go/tools/record/test
    funlen:
      lines: -1
      statements: 65
    gocognit:
      min-complexity: 40
    goconst:
      min-occurrences: 5
    govet:
      enable-all: true
      disable:
        - fieldalignment
    tagliatelle:
      case:
        rules:
          json: snake

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      # We can't parallelize these tests because they share the same configuration map when the test runs
      # and maps are not thread-safe.
      - path: internal/configuration/configuration_test\.go
        linters:
          - paralleltest

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofmt:
      rewrite-rules:
        - pattern: "interface{}"
          replacement: "any"
        - pattern: "a[b:len(a)]"
          replacement: "a[b:]"
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/persona-id/proxysql-agent/
  exclusions:
    generated: lax

run:
  tests: true
