apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac.yaml
  - secret.yaml
  - service-core.yaml
  - service-proxysql.yaml
  - deployment-core.yaml
  - deployment-satellite.yaml
