apiVersion: v1
kind: Secret
metadata:
  name: proxysql-passwords
  namespace: proxysql
  labels:
    app: proxysql
    app.kubernetes.io/part-of: proxysql-agent-smoke
type: Opaque
stringData:
  admin: admin
  radmin: radmin
